/*
 * HAL_CLCD_config.h
 *
 *  Created on: Apr 26, 2024
 *      Author: msaeed
 */

#ifndef HAL_03_CLCD_HAL_CLCD_CONFIG_H_
#define HAL_03_CLCD_HAL_CLCD_CONFIG_H_

// CLCD_4BIT_MODE or CLCD_8BIT_MODE
#define CLCD_u8_MODE CLCD_8BIT_MODE

#define CLCD_u8_DATA_PORT	DIO_PORTA
#define CLCD_u8_CTRL_PORT	DIO_PORTB

#if CLCD_u8_MODE == CLCD_4BIT_MODE
#define CLCD_u8_DATA_PIN_0 DIO_PIN_4
#define CLCD_u8_DATA_PIN_1 DIO_PIN_5
#define CLCD_u8_DATA_PIN_2 DIO_PIN_6
#define CLCD_u8_DATA_PIN_3 DIO_PIN_7
#endif

#define CLCD_u8_RS_PIN	DIO_PIN_2
#define CLCD_u8_RW_PIN	DIO_PIN_1
#define CLCD_u8_E_PIN	DIO_PIN_0

#endif /* 01_HAL_03_CLCD_HAL_CLCD_CONFIG_H_ */
